music/urls.py
from django.urls import path
from . import views

app_name = 'music'
urlpatterns = [

    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('', views.IndexView.as_view(), name='index'),

    path('album/add', views.AlbumCreate.as_view(), name='addalbum'),

    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name='updatealbum'),

    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='deletealbum'),

    path('register/', views.UserFormView.as_view(), name='register')



]

untitled6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title + '-' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=100)
    song_name = models.CharField(max_length=500)

    def __str__(self):
        return self.song_name

music/forms.py
from django.contrib.auth.models import User
from django import forms


class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album
from django.urls import reverse_lazy
from .forms import Userform
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View


class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'title', 'genre', 'album_logo']


class AlbumUpdate (UpdateView):
    model = Album
    fields = ['artist', 'title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = Userform
    template_name = 'music/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add Album {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="#" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        MusicLib
        {% endblock %}
    </title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link type="text/css" href="{% static 'music/style.css' %}" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class=" navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=" .navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class=" navbar-brand" href="{% url 'music:index' %}">MusicLib</a>
            </div>
            <div class="collapse navbar-collapse" id="#topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"> </span>&nbsp;Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:addalbum' %}">
                            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp;Add Album
                        </a>
                    </li>
                    <li class="">
                        <a href="">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp;Log Out
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>

</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}
Album details
{% endblock %}

{% block body %}
{% load static %}

<h1>{{album.title}}</h1>
<h2>{{album.artist}}</h2>


{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
  <div class=" col-sm-offset-2  col-sm-10 ">
    <span class="text-danger small">{{field.errors}}</span>
  </div>
  <label class="control-label col-sm-2">{{field.label_tag}}</label>
  <div class="col-sm-10">{{field}}</div>
</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}
<div class=" albums-container container-fluid">
    <div class="row">
        {% if object_list%}
        {% for album in object_list %}
        <div class="col-sm-4 col-lg-2">
            <div class="thumbnail">
                <a href=" {% url 'music:detail' album.id %}"><img src="{{album.album_logo.url}}" class="img-responsive">
                </a>
                <div class="caption">
                    <h2>{{album.title}}</h2>
                    <h4>{{album.artist}}</h4>
                    <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                    <form action="{% url 'music:deletealbum' album.id %}" method="post" style="display: inline-block;">
                        {% csrf_token %}
                        <input type="hidden" name="album_id" value="{{album.id}}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
        {%else%}
        <h1>You don't have any album</h1>
        {% endif%}
    </div>
</div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register User {% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a new account</h3>
                    <form class="form-horizontal" action="#" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}